services:
  postgres:
    image: postgres:15
    container_name: dvdrental_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dvdrental
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dvdrental.tar:/docker-entrypoint-initdb.d/dvdrental.tar
    ports:
      - "5432:5432"

volumes:
  pgdata:

